{
 "title": "DISTRISE",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Success QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(success_total{job=\"aggregator\"}[1m])) by (client)",
     "legendFormat": "aggregator"
    },
    {
     "expr": "sum(rate(success_total{job=\"aggregator-consumer\"}[1m]))",
     "legendFormat": "consumer"
    },
    {}
   ]
  },
  { "title": "Aggregator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Aggregator Success QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(success_total{job=\"aggregator\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregator Fail QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fail_total{job=\"aggregator\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(processed_duration_second_sum{job=\"aggregator\"}[1m])) / sum(rate(processed_duration_second_count{job=\"aggregator\"}[1m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Consume Success QPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(success_total{job=\"aggregator-consumer\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consume Fail QPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fail_total{job=\"aggregator-consumer\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consume Avg Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(processed_duration_second_sum{job=\"aggregator-consumer\"}[1m])) / sum(rate(processed_duration_second_count{job=\"aggregator-consumer\"}[1m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Relay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Relay Success QPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(success_total{job=\"relay\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay Fail QPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fail_total{job=\"relay\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay Avg Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(processed_duration_second_sum{job=\"relay\"}[1m])) / sum(rate(processed_duration_second_count{job=\"relay\"}[1m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}