// Code generated by MockGen. DO NOT EDIT.
// Source: ./store.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	internal "github.com/a5347354/rise-workshop/internal"
	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockStore) Insert(ctx context.Context, event internal.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockStoreMockRecorder) Insert(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockStore)(nil).Insert), ctx, event)
}

// SearchByContent mocks base method.
func (m *MockStore) SearchByContent(ctx context.Context, keyword string) ([]internal.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByContent", ctx, keyword)
	ret0, _ := ret[0].([]internal.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByContent indicates an expected call of SearchByContent.
func (mr *MockStoreMockRecorder) SearchByContent(ctx, keyword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByContent", reflect.TypeOf((*MockStore)(nil).SearchByContent), ctx, keyword)
}

// MockAsyncStore is a mock of AsyncStore interface.
type MockAsyncStore struct {
	ctrl     *gomock.Controller
	recorder *MockAsyncStoreMockRecorder
}

// MockAsyncStoreMockRecorder is the mock recorder for MockAsyncStore.
type MockAsyncStoreMockRecorder struct {
	mock *MockAsyncStore
}

// NewMockAsyncStore creates a new mock instance.
func NewMockAsyncStore(ctrl *gomock.Controller) *MockAsyncStore {
	mock := &MockAsyncStore{ctrl: ctrl}
	mock.recorder = &MockAsyncStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAsyncStore) EXPECT() *MockAsyncStoreMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockAsyncStore) Insert(ctx context.Context, event internal.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockAsyncStoreMockRecorder) Insert(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAsyncStore)(nil).Insert), ctx, event)
}
